[2025-05-10T13:11:16.732+0000] {processor.py:161} INFO - Started process (PID=657) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:11:16.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:11:16.734+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:11:16.734+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:11:16.750+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:11:16.746+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:11:16.754+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:11:16.836+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.131 seconds
[2025-05-10T13:11:46.992+0000] {processor.py:161} INFO - Started process (PID=662) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:11:46.993+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:11:46.994+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:11:46.993+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:11:47.011+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:11:47.008+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:11:47.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:11:47.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.056 seconds
[2025-05-10T13:12:17.139+0000] {processor.py:161} INFO - Started process (PID=667) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:12:17.140+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:12:17.141+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:12:17.141+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:12:17.157+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:12:17.154+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:12:17.158+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:12:17.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.042 seconds
[2025-05-10T13:12:47.336+0000] {processor.py:161} INFO - Started process (PID=672) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:12:47.337+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:12:47.338+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:12:47.338+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:12:47.356+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:12:47.352+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:12:47.357+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:12:47.376+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2025-05-10T13:13:17.488+0000] {processor.py:161} INFO - Started process (PID=677) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:13:17.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:13:17.490+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:13:17.490+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:13:17.509+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:13:17.505+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:13:17.510+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:13:17.528+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2025-05-10T13:13:47.664+0000] {processor.py:161} INFO - Started process (PID=682) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:13:47.665+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:13:47.666+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:13:47.665+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:13:47.681+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:13:47.678+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:13:47.682+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:13:47.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2025-05-10T13:23:49.067+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:23:49.068+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:23:49.069+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:23:49.069+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:23:49.084+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:23:49.080+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:23:49.085+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:23:49.106+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.044 seconds
[2025-05-10T13:24:19.241+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:24:19.242+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:24:19.244+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:24:19.244+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:24:19.259+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:24:19.256+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:24:19.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:24:19.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.043 seconds
[2025-05-10T13:24:49.398+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:24:49.399+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:24:49.401+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:24:49.400+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:24:49.419+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:24:49.415+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:24:49.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:24:49.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2025-05-10T13:25:19.597+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:25:19.598+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:25:19.600+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:25:19.599+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:25:19.621+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:25:19.616+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:25:19.623+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:25:19.644+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.052 seconds
[2025-05-10T13:25:49.760+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:25:49.761+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:25:49.763+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:25:49.762+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:25:49.778+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:25:49.775+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:25:49.780+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:25:49.799+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.044 seconds
[2025-05-10T13:26:19.917+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:26:19.917+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:26:19.919+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:26:19.919+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:26:19.937+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:26:19.934+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:26:19.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:26:19.955+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.043 seconds
[2025-05-10T13:26:50.083+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:26:50.084+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:26:50.086+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:26:50.086+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:26:50.112+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:26:50.106+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:26:50.113+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:26:50.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.058 seconds
[2025-05-10T13:27:20.245+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:27:20.246+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:27:20.248+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:27:20.247+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:27:20.268+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:27:20.263+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:27:20.270+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:27:20.293+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.054 seconds
[2025-05-10T13:27:50.425+0000] {processor.py:161} INFO - Started process (PID=202) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:27:50.426+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:27:50.427+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:27:50.427+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:27:50.442+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:27:50.439+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:27:50.443+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:27:50.460+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.040 seconds
[2025-05-10T13:28:20.583+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:28:20.584+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:28:20.585+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:28:20.585+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:28:20.605+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:28:20.600+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:28:20.606+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:28:20.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.051 seconds
[2025-05-10T13:28:50.764+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:28:50.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:28:50.766+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:28:50.766+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:28:50.781+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:28:50.778+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:28:50.782+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:28:50.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.040 seconds
[2025-05-10T13:29:20.918+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:29:20.919+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:29:20.921+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:29:20.920+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:29:20.936+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:29:20.932+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:29:20.938+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:29:20.957+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2025-05-10T13:29:51.123+0000] {processor.py:161} INFO - Started process (PID=222) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:29:51.124+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:29:51.126+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:29:51.125+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:29:51.140+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:29:51.137+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:29:51.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:29:51.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.039 seconds
[2025-05-10T13:30:21.269+0000] {processor.py:161} INFO - Started process (PID=227) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:30:21.270+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:30:21.272+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:30:21.272+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:30:21.289+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:30:21.286+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:30:21.291+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:30:21.307+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.043 seconds
[2025-05-10T13:30:51.436+0000] {processor.py:161} INFO - Started process (PID=232) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:30:51.437+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:30:51.439+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:30:51.439+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:30:51.453+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:30:51.450+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:30:51.454+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:30:51.472+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2025-05-10T13:31:21.587+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:31:21.588+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:31:21.590+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:31:21.589+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:31:21.606+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:31:21.603+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:31:21.608+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:31:21.628+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2025-05-10T13:31:51.762+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:31:51.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:31:51.765+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:31:51.765+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:31:51.780+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:31:51.777+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:31:51.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:31:51.800+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.043 seconds
[2025-05-10T13:32:21.926+0000] {processor.py:161} INFO - Started process (PID=247) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:32:21.927+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:32:21.929+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:32:21.929+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:32:21.948+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:32:21.944+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:32:21.949+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:32:21.970+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.050 seconds
[2025-05-10T13:33:10.645+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:33:10.646+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:33:10.648+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:33:10.648+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:33:10.661+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:33:10.657+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:33:10.662+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:33:10.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.039 seconds
[2025-05-10T13:33:40.827+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:33:40.828+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:33:40.830+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:33:40.829+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:33:40.850+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:33:40.846+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:33:40.851+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:33:40.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.050 seconds
[2025-05-10T13:34:10.992+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:34:10.993+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:34:10.995+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:34:10.994+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:34:11.011+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:34:11.008+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:34:11.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:34:11.030+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.045 seconds
[2025-05-10T13:34:41.159+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:34:41.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:34:41.162+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:34:41.162+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:34:41.181+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:34:41.177+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:34:41.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:34:41.205+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.051 seconds
[2025-05-10T13:37:11.634+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:37:11.635+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:37:11.637+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:37:11.636+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:37:11.652+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:37:11.648+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:37:11.654+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:37:11.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.055 seconds
[2025-05-10T13:37:41.842+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:37:41.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:37:41.845+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:37:41.844+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:37:41.863+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:37:41.859+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:37:41.864+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:37:41.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.047 seconds
[2025-05-10T13:38:12.018+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:38:12.019+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:38:12.021+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:38:12.021+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:38:12.038+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:38:12.035+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:38:12.040+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:38:12.059+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2025-05-10T13:38:42.169+0000] {processor.py:161} INFO - Started process (PID=177) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:38:42.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:38:42.172+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:38:42.172+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:38:42.192+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:38:42.187+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:38:42.194+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:38:42.222+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.059 seconds
[2025-05-10T13:39:12.371+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:39:12.372+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:39:12.374+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:39:12.373+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:39:12.392+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:39:12.388+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:39:12.393+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:39:12.419+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.053 seconds
[2025-05-10T13:39:42.528+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:39:42.529+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:39:42.531+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:39:42.531+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:39:42.549+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:39:42.545+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:39:42.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:39:42.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.056 seconds
[2025-05-10T13:40:12.712+0000] {processor.py:161} INFO - Started process (PID=192) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:40:12.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:40:12.715+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:40:12.714+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:40:12.729+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:40:12.726+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:40:12.730+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:40:12.748+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.041 seconds
[2025-05-10T13:41:24.244+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:41:24.245+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:41:24.246+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:41:24.246+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:41:24.261+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:41:24.258+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:41:24.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:41:24.279+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.040 seconds
[2025-05-10T13:41:54.424+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:41:54.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:41:54.426+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:41:54.426+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:41:54.444+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:41:54.440+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:41:54.445+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:41:54.467+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.048 seconds
[2025-05-10T13:42:24.583+0000] {processor.py:161} INFO - Started process (PID=172) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:42:24.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:42:24.585+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:42:24.585+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:42:24.601+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:42:24.598+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:42:24.603+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:42:24.624+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.046 seconds
[2025-05-10T13:42:54.755+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:42:54.756+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:42:54.757+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:42:54.757+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:42:54.771+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:42:54.767+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/get_data.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/get_data.py", line 5, in <module>
    from pandas_datareader import data as pdr
ModuleNotFoundError: No module named 'pandas_datareader'
[2025-05-10T13:42:54.772+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:42:54.789+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.038 seconds
[2025-05-10T13:43:40.570+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:43:40.571+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:43:40.572+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:43:40.572+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:43:42.410+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:43:42.625+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:43:42.625+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:inflation_data_ingest_fred_only
[2025-05-10T13:43:42.635+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:43:42.635+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:inflation_data_ingest_fred_only
[2025-05-10T13:43:42.641+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:43:42.641+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:inflation_data_ingest_fred_only
[2025-05-10T13:43:42.642+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:43:42.642+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:43:42.651+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:43:42.651+0000] {dag.py:3118} INFO - Creating ORM DAG for inflation_data_ingest_fred_only
[2025-05-10T13:43:42.661+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:43:42.660+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-04-01 00:00:00+00:00, run_after=2025-05-01 00:00:00+00:00
[2025-05-10T13:43:42.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 2.117 seconds
[2025-05-10T13:44:12.877+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:44:12.878+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:44:12.880+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:44:12.880+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:44:13.490+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:44:13.511+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:44:13.511+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:44:13.529+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:44:13.528+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-04-01 00:00:00+00:00, run_after=2025-05-01 00:00:00+00:00
[2025-05-10T13:44:13.546+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.674 seconds
[2025-05-10T13:44:43.719+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:44:43.720+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:44:43.722+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:44:43.722+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:44:44.340+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:44:44.360+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:44:44.360+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:44:44.377+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:44:44.377+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:44:44.394+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.681 seconds
[2025-05-10T13:45:14.561+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:45:14.562+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:45:14.565+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:45:14.564+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:45:15.231+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:45:15.254+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:45:15.253+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:45:15.275+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:45:15.275+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:45:15.304+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.748 seconds
[2025-05-10T13:45:45.468+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:45:45.469+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:45:45.472+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:45:45.471+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:45:46.064+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:45:46.086+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:45:46.084+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:45:46.103+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:45:46.103+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:45:46.128+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.664 seconds
[2025-05-10T13:46:16.314+0000] {processor.py:161} INFO - Started process (PID=213) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:46:16.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:46:16.317+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:46:16.317+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:46:16.981+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:46:17.008+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:46:17.008+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:46:17.026+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:46:17.026+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:46:17.046+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.737 seconds
[2025-05-10T13:46:47.207+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:46:47.208+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:46:47.210+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:46:47.210+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:46:47.812+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:46:47.833+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:46:47.832+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:46:47.851+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:46:47.850+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:46:47.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.669 seconds
[2025-05-10T13:47:18.033+0000] {processor.py:161} INFO - Started process (PID=225) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:47:18.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:47:18.037+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:47:18.036+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:47:18.621+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:47:18.642+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:47:18.642+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:47:18.660+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:47:18.659+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:47:18.677+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.650 seconds
[2025-05-10T13:47:48.859+0000] {processor.py:161} INFO - Started process (PID=231) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:47:48.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:47:48.862+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:47:48.862+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:47:49.477+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:47:49.498+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:47:49.498+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:47:49.522+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:47:49.522+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:47:49.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.688 seconds
[2025-05-10T13:48:19.715+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:48:19.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:48:19.718+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:48:19.717+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:48:20.301+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:48:20.321+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:48:20.321+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:48:20.339+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:48:20.339+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:48:20.356+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.646 seconds
[2025-05-10T13:48:50.448+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:48:50.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:48:50.451+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:48:50.451+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:48:51.033+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:48:51.054+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:48:51.054+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:48:51.073+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:48:51.072+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:48:51.089+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.646 seconds
[2025-05-10T13:49:21.265+0000] {processor.py:161} INFO - Started process (PID=249) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:49:21.266+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:49:21.268+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:49:21.268+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:49:21.935+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:49:21.955+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:49:21.955+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:49:21.973+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:49:21.973+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:49:21.989+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.729 seconds
[2025-05-10T13:49:52.160+0000] {processor.py:161} INFO - Started process (PID=255) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:49:52.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:49:52.163+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:49:52.162+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:49:52.754+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:49:52.777+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:49:52.776+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:49:52.794+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:49:52.794+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:49:52.810+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.655 seconds
[2025-05-10T13:50:22.970+0000] {processor.py:161} INFO - Started process (PID=282) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:50:22.971+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:50:22.973+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:50:22.973+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:50:23.710+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:50:23.730+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:50:23.729+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:50:23.747+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:50:23.747+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:50:23.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.801 seconds
[2025-05-10T13:50:53.946+0000] {processor.py:161} INFO - Started process (PID=288) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:50:53.947+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:50:53.949+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:50:53.949+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:50:54.609+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:50:54.633+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:50:54.633+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:50:54.657+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:50:54.657+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:50:54.689+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.749 seconds
[2025-05-10T13:51:24.873+0000] {processor.py:161} INFO - Started process (PID=294) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:51:24.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:51:24.876+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:51:24.875+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:51:25.467+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:51:25.487+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:51:25.487+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:51:25.505+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:51:25.505+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:51:25.531+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.663 seconds
[2025-05-10T13:51:55.692+0000] {processor.py:161} INFO - Started process (PID=300) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:51:55.693+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:51:55.695+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:51:55.694+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:51:56.386+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:51:56.411+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:51:56.411+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:51:56.430+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:51:56.430+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:51:56.447+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.761 seconds
[2025-05-10T13:52:26.542+0000] {processor.py:161} INFO - Started process (PID=306) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:52:26.544+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:52:26.546+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:52:26.546+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:52:27.281+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:52:27.303+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:52:27.302+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:52:27.324+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:52:27.324+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:52:27.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.807 seconds
[2025-05-10T13:53:00.028+0000] {processor.py:161} INFO - Started process (PID=161) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:53:00.029+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:53:00.030+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:53:00.030+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:53:00.697+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:53:00.729+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:53:00.729+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:53:00.748+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:53:00.748+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:53:00.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.743 seconds
[2025-05-10T13:53:30.941+0000] {processor.py:161} INFO - Started process (PID=167) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:53:30.942+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:53:30.944+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:53:30.944+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:53:31.564+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:53:31.583+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:53:31.583+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:53:31.602+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:53:31.602+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:53:31.618+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.682 seconds
[2025-05-10T13:54:01.785+0000] {processor.py:161} INFO - Started process (PID=194) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:54:01.786+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:54:01.788+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:54:01.787+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:54:02.400+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:54:02.420+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:54:02.420+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:54:02.438+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:54:02.438+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:54:02.454+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.675 seconds
[2025-05-10T13:54:32.612+0000] {processor.py:161} INFO - Started process (PID=200) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:54:32.613+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:54:32.615+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:54:32.615+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:54:33.219+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:54:33.241+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:54:33.240+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:54:33.259+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:54:33.258+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:54:33.281+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.675 seconds
[2025-05-10T13:55:03.461+0000] {processor.py:161} INFO - Started process (PID=206) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:55:03.463+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:55:03.465+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:55:03.464+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:55:04.109+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:55:04.128+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:55:04.128+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:55:04.147+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:55:04.147+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:55:04.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.711 seconds
[2025-05-10T13:55:34.369+0000] {processor.py:161} INFO - Started process (PID=212) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:55:34.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:55:34.372+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:55:34.372+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:55:35.129+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:55:35.153+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:55:35.153+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:55:35.174+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:55:35.174+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:55:35.199+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.835 seconds
[2025-05-10T13:56:05.369+0000] {processor.py:161} INFO - Started process (PID=218) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:56:05.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:56:05.372+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:56:05.372+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:56:05.957+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:56:05.977+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:56:05.977+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:56:05.995+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:56:05.995+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:56:06.020+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.656 seconds
[2025-05-10T13:57:22.834+0000] {processor.py:161} INFO - Started process (PID=162) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:57:22.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:57:22.836+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:57:22.835+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:57:24.584+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:57:24.627+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:57:24.627+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:57:24.648+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:57:24.648+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:57:24.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 1.849 seconds
[2025-05-10T13:57:54.841+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:57:54.842+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:57:54.844+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:57:54.844+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:57:55.433+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:57:55.453+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:57:55.453+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:57:55.471+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:57:55.471+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:57:55.487+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.651 seconds
[2025-05-10T13:58:25.659+0000] {processor.py:161} INFO - Started process (PID=195) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:58:25.660+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:58:25.662+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:58:25.662+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:58:26.289+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:58:26.311+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:58:26.310+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:58:26.328+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:58:26.328+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:58:26.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.695 seconds
[2025-05-10T13:58:56.510+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/get_data.py
[2025-05-10T13:58:56.511+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/get_data.py for tasks to queue
[2025-05-10T13:58:56.513+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:58:56.513+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/get_data.py
[2025-05-10T13:58:57.166+0000] {processor.py:840} INFO - DAG(s) 'inflation_data_ingest_fred_only' retrieved from /opt/airflow/dags/get_data.py
[2025-05-10T13:58:57.186+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:58:57.186+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2025-05-10T13:58:57.206+0000] {logging_mixin.py:188} INFO - [2025-05-10T13:58:57.206+0000] {dag.py:3954} INFO - Setting next_dagrun for inflation_data_ingest_fred_only to 2025-05-01 00:00:00+00:00, run_after=2025-06-01 00:00:00+00:00
[2025-05-10T13:58:57.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/get_data.py took 0.720 seconds
