[2025-06-18T16:55:29.296+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T16:55:29.362+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kse100_forecasting.fetch_gold manual__2025-06-18T16:55:19.331260+00:00 [queued]>
[2025-06-18T16:55:29.385+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kse100_forecasting.fetch_gold manual__2025-06-18T16:55:19.331260+00:00 [queued]>
[2025-06-18T16:55:29.386+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2025-06-18T16:55:29.462+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): fetch_gold> on 2025-06-18 16:55:19.331260+00:00
[2025-06-18T16:55:29.506+0000] {standard_task_runner.py:63} INFO - Started process 3335 to run task
[2025-06-18T16:55:29.518+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kse100_forecasting', 'fetch_gold', 'manual__2025-06-18T16:55:19.331260+00:00', '--job-id', '996', '--raw', '--subdir', 'DAGS_FOLDER/kse100_forecasting_dag.py', '--cfg-path', '/tmp/tmprnmmqszt']
[2025-06-18T16:55:29.526+0000] {standard_task_runner.py:91} INFO - Job 996: Subtask fetch_gold
[2025-06-18T16:55:29.641+0000] {task_command.py:426} INFO - Running <TaskInstance: kse100_forecasting.fetch_gold manual__2025-06-18T16:55:19.331260+00:00 [running]> on host 57c57e92cb28
[2025-06-18T16:55:29.863+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kse100_forecasting' AIRFLOW_CTX_TASK_ID='fetch_gold' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T16:55:19.331260+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T16:55:19.331260+00:00'
[2025-06-18T16:55:29.875+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T16:55:29.898+0000] {ingest.py:65} INFO - Fetching GC=F from Yahoo Finance...
[2025-06-18T16:55:40.865+0000] {multi.py:184} ERROR - 
1 Failed download:
[2025-06-18T16:55:40.865+0000] {multi.py:197} ERROR - ['GC=F']: Timeout('Failed to perform, curl: (28) Operation timed out after 10002 milliseconds with 29547 bytes received. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.')
[2025-06-18T16:55:40.885+0000] {ingest.py:112} ERROR - Error fetching GC=F: No data downloaded for ticker 'GC=F'
[2025-06-18T16:55:40.885+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T16:55:40.886+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/kse_modules/ingest.py", line 83, in fetch_yahoo_finance
    raise ValueError(f"No data downloaded for ticker '{ticker}'")
ValueError: No data downloaded for ticker 'GC=F'
[2025-06-18T16:55:40.901+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=kse100_forecasting, task_id=fetch_gold, run_id=manual__2025-06-18T16:55:19.331260+00:00, execution_date=20250618T165519, start_date=20250618T165529, end_date=20250618T165540
[2025-06-18T16:55:40.928+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 996 for task fetch_gold (No data downloaded for ticker 'GC=F'; 3335)
[2025-06-18T16:55:40.952+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T16:55:40.961+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
