[2025-06-19T08:42:49.148+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-19T08:42:49.173+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kse100_forecasting.train_stacked manual__2025-06-19T08:42:26.783185+00:00 [queued]>
[2025-06-19T08:42:49.183+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kse100_forecasting.train_stacked manual__2025-06-19T08:42:26.783185+00:00 [queued]>
[2025-06-19T08:42:49.183+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-06-19T08:42:49.197+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_stacked> on 2025-06-19 08:42:26.783185+00:00
[2025-06-19T08:42:49.203+0000] {standard_task_runner.py:63} INFO - Started process 497 to run task
[2025-06-19T08:42:49.206+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'kse100_forecasting', 'train_stacked', 'manual__2025-06-19T08:42:26.783185+00:00', '--job-id', '1058', '--raw', '--subdir', 'DAGS_FOLDER/kse100_forecasting_dag.py', '--cfg-path', '/tmp/tmpjtm8fhvw']
[2025-06-19T08:42:49.208+0000] {standard_task_runner.py:91} INFO - Job 1058: Subtask train_stacked
[2025-06-19T08:42:49.249+0000] {task_command.py:426} INFO - Running <TaskInstance: kse100_forecasting.train_stacked manual__2025-06-19T08:42:26.783185+00:00 [running]> on host 57c57e92cb28
[2025-06-19T08:42:49.361+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kse100_forecasting' AIRFLOW_CTX_TASK_ID='train_stacked' AIRFLOW_CTX_EXECUTION_DATE='2025-06-19T08:42:26.783185+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-19T08:42:26.783185+00:00'
[2025-06-19T08:42:49.362+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-19T08:42:52.668+0000] {logging_mixin.py:188} INFO - Stacked: R2=-0.5431, MSE=38934780.5538, MAE=5020.5186
[2025-06-19T08:42:52.673+0000] {logging_mixin.py:188} INFO - Error predicting on full dataset (Stacked): [Errno 2] No such file or directory: '/opt/***/data/transformed_data.csv'
[2025-06-19T08:42:52.674+0000] {python.py:237} INFO - Done. Returned value was: ('/opt/***/dataKse/models/kse_stacked_model.pkl', '/opt/***/dataKse/models/kse_stacked_metrics.csv')
[2025-06-19T08:42:52.674+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-19T08:42:52.695+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=kse100_forecasting, task_id=train_stacked, run_id=manual__2025-06-19T08:42:26.783185+00:00, execution_date=20250619T084226, start_date=20250619T084249, end_date=20250619T084252
[2025-06-19T08:42:52.750+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-19T08:42:52.766+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-19T08:42:52.768+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
