[2025-06-18T17:32:10.983+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T17:32:11.016+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usdpkr_forecasting.train_stacked manual__2025-06-18T17:15:18.237055+00:00 [queued]>
[2025-06-18T17:32:11.033+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usdpkr_forecasting.train_stacked manual__2025-06-18T17:15:18.237055+00:00 [queued]>
[2025-06-18T17:32:11.033+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-06-18T17:32:11.053+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_stacked> on 2025-06-18 17:15:18.237055+00:00
[2025-06-18T17:32:11.069+0000] {standard_task_runner.py:63} INFO - Started process 5152 to run task
[2025-06-18T17:32:11.072+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'usdpkr_forecasting', 'train_stacked', 'manual__2025-06-18T17:15:18.237055+00:00', '--job-id', '1027', '--raw', '--subdir', 'DAGS_FOLDER/usdpkr_forecasting_dag.py', '--cfg-path', '/tmp/tmpzv0hkylh']
[2025-06-18T17:32:11.074+0000] {standard_task_runner.py:91} INFO - Job 1027: Subtask train_stacked
[2025-06-18T17:32:11.129+0000] {task_command.py:426} INFO - Running <TaskInstance: usdpkr_forecasting.train_stacked manual__2025-06-18T17:15:18.237055+00:00 [running]> on host 57c57e92cb28
[2025-06-18T17:32:11.328+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='usdpkr_forecasting' AIRFLOW_CTX_TASK_ID='train_stacked' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T17:15:18.237055+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T17:15:18.237055+00:00'
[2025-06-18T17:32:11.329+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T17:32:16.924+0000] {logging_mixin.py:188} INFO - Stacked: R2=0.6971, MSE=562.3060, MAE=15.1701
[2025-06-18T17:32:16.934+0000] {logging_mixin.py:188} INFO - Error predicting on full dataset (Stacked): [Errno 2] No such file or directory: '/opt/***/data/transformed_data.csv'
[2025-06-18T17:32:16.935+0000] {python.py:237} INFO - Done. Returned value was: ('/opt/***/data/models/usdpkr_stacked_model.pkl', '/opt/***/data/models/usdpkr_stacked_metrics.csv')
[2025-06-18T17:32:16.936+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T17:32:16.958+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=usdpkr_forecasting, task_id=train_stacked, run_id=manual__2025-06-18T17:15:18.237055+00:00, execution_date=20250618T171518, start_date=20250618T173211, end_date=20250618T173216
[2025-06-18T17:32:17.010+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-18T17:32:17.024+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-18T17:32:17.028+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
