[2025-06-18T13:35:55.440+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-18T13:35:55.475+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: usdpkr_forecasting_modular.train_stacked manual__2025-06-18T13:35:35.483358+00:00 [queued]>
[2025-06-18T13:35:55.485+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: usdpkr_forecasting_modular.train_stacked manual__2025-06-18T13:35:35.483358+00:00 [queued]>
[2025-06-18T13:35:55.485+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-06-18T13:35:55.497+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_stacked> on 2025-06-18 13:35:35.483358+00:00
[2025-06-18T13:35:55.503+0000] {standard_task_runner.py:63} INFO - Started process 8425 to run task
[2025-06-18T13:35:55.505+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'usdpkr_forecasting_modular', 'train_stacked', 'manual__2025-06-18T13:35:35.483358+00:00', '--job-id', '766', '--raw', '--subdir', 'DAGS_FOLDER/usdpkr_forecasting_dag.py', '--cfg-path', '/tmp/tmpzhel4w79']
[2025-06-18T13:35:55.508+0000] {standard_task_runner.py:91} INFO - Job 766: Subtask train_stacked
[2025-06-18T13:35:55.551+0000] {task_command.py:426} INFO - Running <TaskInstance: usdpkr_forecasting_modular.train_stacked manual__2025-06-18T13:35:35.483358+00:00 [running]> on host 9c4806d77c92
[2025-06-18T13:35:55.665+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='usdpkr_forecasting_modular' AIRFLOW_CTX_TASK_ID='train_stacked' AIRFLOW_CTX_EXECUTION_DATE='2025-06-18T13:35:35.483358+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-06-18T13:35:35.483358+00:00'
[2025-06-18T13:35:55.666+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-18T13:35:55.680+0000] {model_steps.py:897} ERROR - Error in train_stacked_model: invalid load key, 'f'.
[2025-06-18T13:35:55.681+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-18T13:35:55.681+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/inflation_modules/model_steps.py", line 853, in train_stacked_model
    selected_data = pickle.load(f)
                    ^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, 'f'.
[2025-06-18T13:35:55.691+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=usdpkr_forecasting_modular, task_id=train_stacked, run_id=manual__2025-06-18T13:35:35.483358+00:00, execution_date=20250618T133535, start_date=20250618T133555, end_date=20250618T133555
[2025-06-18T13:35:55.709+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 766 for task train_stacked (invalid load key, 'f'.; 8425)
[2025-06-18T13:35:55.718+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-18T13:35:55.727+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
